In [1]:
#importing libraries
import pandas as pd
import numpy as np
import seaborn as sn
import matplotlib.pyplot as matplot
import re
import logging
import os

In [ ]:
#reading excel with multiple sheets and selecting a specific sheet
xls = pd.ExcelFile('csv_data/data1.xlsx')
demo_df = pd.read_excel(xls,'Demographics',skiprows=1, na_values=)
demo_df = demo_df.iloc[:,1:]

In [ ]:
#reading excel with multiple sheets and selecting a specific sheet
xls = pd.ExcelFile('csv_data/data1.xlsx')
demo_df_numeric = pd.read_excel(xls,'Numeric Demographic',skiprows=1)
demo_df_numeric

,ID,List of Countries,"What is your year of birth (Just the year, e.g. 1995) ?",How do you describe yourself? - Selected Choice,How do you describe yourself? - Prefer to self-describe - Text,What is your first degree subject area?,How many years work experience do you have?,What sectors have you worked in?,Previous experiences of team working in study and work,"Based on experience or feeling, my expectations for this module are that: - I will enjoy working in the team",...,Why are you doing this module? \nScore by the extent to which the statement corresponds with how you feel about it - 7. Because it is something that I have to do,Why are you doing this module? \nScore by the extent to which the statement corresponds with how you feel about it - 8. I am doing this module but I am not sure if it is worth it,Why are you doing this module? \nScore by the extent to which the statement corresponds with how you feel about it - 9. Because this module looks fun,Why are you doing this module? \nScore by the extent to which the statement corresponds with how you feel about it - 10. By personal decision,Why are you doing this module? \nScore by the extent to which the statement corresponds with how you feel about it - 11. Because I don’t have any choice,Why are you doing this module? \nScore by the extent to which the statement corresponds with how you feel about it - 12. I don’t know; I don’t see what this module brings me,Why are you doing this module? \nScore by the extent to which the statement corresponds with how you feel about it - 13. Because I feel good about this module,Why are you doing this module? \nScore by the extent to which the statement corresponds with how you feel about it - 14. Because I believe that this module is important for me,Why are you doing this module? \nScore by the extent to which the statement corresponds with how you feel about it - 15. Because I feel that I have to do it,"Why are you doing this module? \nScore by the extent to which the statement corresponds with how you feel about it - 16. I am doing this module, but I am not sure it is a good thing to pursue it"
0,1,126,1996,1,NaN,18.0,5.0,"6,12",2.0,5.0,...,7.0,5.0,7.0,7.0,1.0,4.0,7.0,7.0,7.0,3.0
1,2,126,1996,1,NaN,12.0,3.0,10,3.0,5.0,...,7.0,1.0,3.0,1.0,4.0,1.0,5.0,6.0,4.0,1.0
2,3,126,1990,2,NaN,20.0,2.0,18,2.0,4.0,...,4.0,1.0,4.0,6.0,1.0,1.0,4.0,6.0,4.0,1.0
3,4,126,1991,1,NaN,20.0,6.0,"10,14",4.0,5.0,...,1.0,1.0,7.0,7.0,1.0,1.0,7.0,7.0,4.0,1.0
4,5,130,1998,1,NaN,24.0,0.0,NaN,2.0,3.0,...,2.0,3.0,5.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,208,78,1992,1,NaN,25.0,10.0,"11,17",4.0,5.0,...,7.0,6.0,7.0,5.0,1.0,1.0,6.0,7.0,5.0,1.0
208,209,14,1996,2,NaN,24.0,4.0,11,3.0,4.0,...,2.0,2.0,4.0,6.0,1.0,2.0,5.0,7.0,7.0,1.0
209,210,164,1996,2,NaN,17.0,1.0,13,2.0,2.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
210,211,118,1998,2,NaN,17.0,1.0,19,3.0,5.0,...,7.0,1.0,6.0,7.0,1.0,1.0,6.0,7.0,6.0,1.0
211,212,187,2001,1,NaN,17.0,2.0,"10,11,17,19",4.0,4.0,...,1.0,1.0,4.0,7.0,1.0,1.0,5.0,7.0,5.0,1.0

In [4]:
#reading excel with multiple sheets and selecting a specific sheet
xls = pd.ExcelFile('csv_data/data1.xlsx')
Retro_numeric = pd.read_excel(xls,'Retro numeric',skiprows=1)
Retro_numeric

,"Please enter your student ID\n\nWe will use this to connect your data together, but will not share it or use it to identify you personally beyond the end of the study",Please reflect on your team's performance in the module - I really enjoyed working in the team,Please reflect on your team's performance in the module - Team communication was highly effective,Please reflect on your team's performance in the module - Team communication was very frequent,Please reflect on your team's performance in the module - We bonded personally as well as professionally,Please reflect on your team's performance in the module - We tended to collaborate together on the same tasks,Please reflect on your team's performance in the module - We tended to work on separate tasks and link them together later on,Please reflect on your team's performance in the module - I feel I have developed my professional skills as a result of the team project,Please reflect on your team's performance in the module - I feel I have developed my team working skills and my approach to collaboration as a result of the team project,Please reflect on your team's performance in the module - We adjusted the project regularly as we went along,Please reflect on your team's performance in the module - We stuck to our original project plan,"Please reflect on your team's performance in the module - Overall, I am pleased with our end result",Please add some further comments about things that you felt went well,Please add some further comments about things you felt did not go well or that the team could have done better,"On average over the term, how many hours per week outside of the timetabled classes do you think you spent on the project?"
0,3,4.0,4.0,4.0,3.0,3.0,4.0,4.0,4.0,4.0,5.0,5.0,Our supervisor was fantastic.,Not everyone on the team collaborated fully.,10.0
1,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5,3.0,4.0,5.0,2.0,2.0,5.0,5.0,5.0,4.0,4.0,3.0,Some team members were very involved in the wo...,Some members of the team frequently missed tea...,10.0
3,7,5.0,4.0,4.0,4.0,4.0,5.0,5.0,5.0,5.0,1.0,4.0,The zeal to work in meeting deadlines of submi...,100% Communication was not contributed by all ...,8.0
4,8,4.0,4.0,4.0,2.0,4.0,4.0,3.0,4.0,4.0,3.0,4.0,NaN,NaN,5.0
5,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,14,5.0,5.0,4.0,5.0,5.0,5.0,5.0,5.0,4.0,5.0,5.0,Team collaboration was perfect.,We could attend online meetings instead of off...,6.0
7,18,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,The team showed concerns in one another's pers...,I felt the team could have showed even much be...,6.0
8,22,4.0,4.0,4.0,4.0,5.0,5.0,4.0,5.0,4.0,4.0,4.0,We worked quite well together on trying to get...,One of the group members did not show up at al...,3.0
9,24,5.0,5.0,5.0,5.0,4.0,4.0,4.0,4.0,5.0,3.0,5.0,"I feel we were able to worked well as a team, ...",I would have been helpful if our initial surve...,10.0
10,27,4.0,5.0,4.0,4.0,4.0,5.0,5.0,5.0,5.0,5.0,5.0,NaN,NaN,10.0
11,33,5.0,4.0,4.0,5.0,4.0,4.0,4.0,4.0,5.0,3.0,5.0,I ALSO UNDERSTAND MY WEAKNESS AND STRENGTH,OUR ORIGINAL PROJECT WAS CHANGED AS ARESULT OF...,4.0
12,34,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,All went very nicely and smoothly,Time consuming,15.0
13,47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,55,5.0,5.0,5.0,5.0,5.0,4.0,5.0,5.0,4.0,5.0,5.0,We worked well in our group and there was cons...,what the team could have done better is by kee...,14.0
16,58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,60,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,NaN,NaN,3.0
19,61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,67,4.0,4.0,4.0,4.0,4.0,5.0,5.0,5.0,2.0,5.0,5.0,we were stick to original problem and outcome.,"if we would have invloved more ,the result we ...",4.0
22,68,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,70,4.0,5.0,5.0,4.0,4.0,3.0,4.0,4.0,5.0,3.0,5.0,"Although we had our differences, the team real...","Well, being from different backgrounds came wi...",4.0
24,71,4.0,4.0,4.0,4.0,3.0,5.0,5.0,5.0,5.0,5.0,5.0,NaN,NaN,8.0
25,74,5.0,5.0,5.0,4.0,5.0,5.0,5.0,5.0,5.0,1.0,5.0,Team members prompt response to change all thr...,Nothing yet,14.0
26,75,5.0,5.0,5.0,4.0,4.0,5.0,5.0,5.0,5.0,5.0,5.0,Effective communication and teamwork,"We could have done better, if other team membe...",2.0
27,78,2.0,3.0,4.0,4.0,2.0,4.0,4.0,4.0,2.0,3.0,3.0,gave me an opportunity to learn more about the...,module is bias towards people with data scienc...,10.0
28,81,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,3.0,5.0,It was great experience working in team,data was not available but we managed,10.0
29,83,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,i'm not happy with the project work at all,the fact that everyones grade in the team has ...,42.0
30,86,5.0,3.0,3.0,5.0,5.0,5.0,5.0,5.0,4.0,5.0,5.0,I learned about about open banking which I nev...,Our project management was a disaster. We were...,1.5
31,89,3.0,3.0,2.0,4.0,4.0,5.0,5.0,5.0,3.0,2.0,5.0,The things I felt went well is even the collab...,Somehow I felt that the team are just complain...,40.0
32,97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,104,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,106,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,109,5.0,5.0,4.0,3.0,4.0,4.0,5.0,5.0,4.0,3.0,5.0,NaN,NaN,5.0

In [3]:
#reading excel with multiple sheets and selecting a specific sheetx
xls = pd.ExcelFile('csv_data/data1.xlsx')
Retrospective = pd.read_excel(xls,'Retrospective',skiprows=1)
Retrospective

,"Please enter your student ID\n\nWe will use this to connect your data together, but will not share it or use it to identify you personally beyond the end of the study",Please reflect on your team's performance in the module - I really enjoyed working in the team,Please reflect on your team's performance in the module - Team communication was highly effective,Please reflect on your team's performance in the module - Team communication was very frequent,Please reflect on your team's performance in the module - We bonded personally as well as professionally,Please reflect on your team's performance in the module - We tended to collaborate together on the same tasks,Please reflect on your team's performance in the module - We tended to work on separate tasks and link them together later on,Please reflect on your team's performance in the module - I feel I have developed my professional skills as a result of the team project,Please reflect on your team's performance in the module - I feel I have developed my team working skills and my approach to collaboration as a result of the team project,Please reflect on your team's performance in the module - We adjusted the project regularly as we went along,Please reflect on your team's performance in the module - We stuck to our original project plan,"Please reflect on your team's performance in the module - Overall, I am pleased with our end result",Please add some further comments about things that you felt went well,Please add some further comments about things you felt did not go well or that the team could have done better,"On average over the term, how many hours per week outside of the timetabled classes do you think you spent on the project?"
0,3,Somewhat agree,Somewhat agree,Somewhat agree,Neither agree nor disagree,Neither agree nor disagree,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,Strongly agree,Strongly agree,Our supervisor was fantastic.,Not everyone on the team collaborated fully.,10.0
1,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5,Neither agree nor disagree,Somewhat agree,Strongly agree,Somewhat disagree,Somewhat disagree,Strongly agree,Strongly agree,Strongly agree,Somewhat agree,Somewhat agree,Neither agree nor disagree,Some team members were very involved in the wo...,Some members of the team frequently missed tea...,10.0
3,7,Strongly agree,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly disagree,Somewhat agree,The zeal to work in meeting deadlines of submi...,100% Communication was not contributed by all ...,8.0
4,8,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat disagree,Somewhat agree,Somewhat agree,Neither agree nor disagree,Somewhat agree,Somewhat agree,Neither agree nor disagree,Somewhat agree,NaN,NaN,5.0
5,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,14,Strongly agree,Strongly agree,Somewhat agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Somewhat agree,Strongly agree,Strongly agree,Team collaboration was perfect.,We could attend online meetings instead of off...,6.0
7,18,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,The team showed concerns in one another's pers...,I felt the team could have showed even much be...,6.0
8,22,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,Strongly agree,Strongly agree,Somewhat agree,Strongly agree,Somewhat agree,Somewhat agree,Somewhat agree,We worked quite well together on trying to get...,One of the group members did not show up at al...,3.0
9,24,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,Strongly agree,Neither agree nor disagree,Strongly agree,"I feel we were able to worked well as a team, ...",I would have been helpful if our initial surve...,10.0
10,27,Somewhat agree,Strongly agree,Somewhat agree,Somewhat agree,Somewhat agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,NaN,NaN,10.0
11,33,Strongly agree,Somewhat agree,Somewhat agree,Strongly agree,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,Strongly agree,Neither agree nor disagree,Strongly agree,I ALSO UNDERSTAND MY WEAKNESS AND STRENGTH,OUR ORIGINAL PROJECT WAS CHANGED AS ARESULT OF...,4.0
12,34,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,All went very nicely and smoothly,Time consuming,15.0
13,47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,55,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Somewhat agree,Strongly agree,Strongly agree,Somewhat agree,Strongly agree,Strongly agree,We worked well in our group and there was cons...,what the team could have done better is by kee...,14.0
16,58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,60,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,NaN,NaN,3.0
19,61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,67,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,Strongly agree,Strongly agree,Strongly agree,Somewhat disagree,Strongly agree,Strongly agree,we were stick to original problem and outcome.,"if we would have invloved more ,the result we ...",4.0
22,68,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,70,Somewhat agree,Strongly agree,Strongly agree,Somewhat agree,Somewhat agree,Neither agree nor disagree,Somewhat agree,Somewhat agree,Strongly agree,Neither agree nor disagree,Strongly agree,"Although we had our differences, the team real...","Well, being from different backgrounds came wi...",4.0
24,71,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,Neither agree nor disagree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,NaN,NaN,8.0
25,74,Strongly agree,Strongly agree,Strongly agree,Somewhat agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly disagree,Strongly agree,Team members prompt response to change all thr...,Nothing yet,14.0
26,75,Strongly agree,Strongly agree,Strongly agree,Somewhat agree,Somewhat agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Effective communication and teamwork,"We could have done better, if other team membe...",2.0
27,78,Somewhat disagree,Neither agree nor disagree,Somewhat agree,Somewhat agree,Somewhat disagree,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat disagree,Neither agree nor disagree,Neither agree nor disagree,gave me an opportunity to learn more about the...,module is bias towards people with data scienc...,10.0
28,81,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Neither agree nor disagree,Strongly agree,It was great experience working in team,data was not available but we managed,10.0
29,83,Strongly disagree,Strongly disagree,Strongly disagree,Strongly disagree,Strongly disagree,Strongly disagree,Strongly disagree,Strongly disagree,Strongly disagree,Strongly disagree,Strongly disagree,i'm not happy with the project work at all,the fact that everyones grade in the team has ...,42.0
30,86,Strongly agree,Neither agree nor disagree,Neither agree nor disagree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Somewhat agree,Strongly agree,Strongly agree,I learned about about open banking which I nev...,Our project management was a disaster. We were...,1.5
31,89,Neither agree nor disagree,Neither agree nor disagree,Somewhat disagree,Somewhat agree,Somewhat agree,Strongly agree,Strongly agree,Strongly agree,Neither agree nor disagree,Somewhat disagree,Strongly agree,The things I felt went well is even the collab...,Somehow I felt that the team are just complain...,40.0
32,97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,104,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,106,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,109,Strongly agree,Strongly agree,Somewhat agree,Neither agree nor disagree,Somewhat agree,Somewhat agree,Strongly agree,Strongly agree,Somewhat agree,Neither agree nor disagree,Strongly agree,NaN,NaN,5.0

In [21]:
week1 = pd.read_csv('csv_data/week1.csv')
week2 = pd.read_csv('csv_data/week2.csv')

In [24]:
week1 = week1.iloc[:, 4:]
week2 = week2.iloc[:, 4:]

In [27]:
df = [week1, week2]

In [28]:
pd.concat([week1, week2] ,ignore_index=True)

,what_is_your_first_degree_subject_area,student_id,date_range__week_1,monday,tuesday,wednesday,thursday,friday,saturday,sunday,...,module_information_handbook1,reading_list2,week_12,week_22,unnamed_40,date_range__week_2,week_3_,week_2_,week_3,week_3.1
0,"CAH13-01\tArchitecture, building and planning",1,03/10/22 - 09/10/22,0.000000,0.005278,0.014722,0.000000,0.000000,0.000000,0.023612,...,NaN,NaN,2022-10-04 15:45:03.544,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CAH07-02\tChemistry,2,03/10/22 - 09/10/22,0.000000,3.117500,0.000000,0.000000,0.000000,0.000000,0.000000,...,2022-10-04 14:02:11.582,NaN,2022-10-04 15:48:38.726,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CAH15-02\tEconomics,3,03/10/22 - 09/10/22,0.019722,1.710833,0.000000,0.000000,0.000000,0.000000,0.000000,...,2022-10-03 21:49:58.608,2022-10-04 14:01:58.086,2022-10-04 14:05:37.424,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,CAH15-02\tEconomics,4,03/10/22 - 09/10/22,0.001667,0.018055,0.000000,0.000000,0.000000,0.000000,0.000000,...,NaN,NaN,2022-10-03 11:15:50.346,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,CAH17-01\tBusiness and management,5,03/10/22 - 09/10/22,0.000000,2.232222,0.052778,0.000000,0.000000,0.000000,0.000000,...,2022-10-05 17:49:47.691,NaN,2022-10-04 15:49:38.697,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,CAH10-01\tEngineering,6,03/10/22 - 09/10/22,0.000000,5.439445,0.000000,0.000000,0.000000,0.000000,0.000000,...,2022-10-04 11:39:42.832,NaN,2022-10-04 12:27:03.171,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,CAH11-01\tComputing,7,03/10/22 - 09/10/22,0.000000,1.549722,0.011667,0.000000,0.000000,0.000000,0.000000,...,2022-10-04 15:32:40.566,NaN,2022-10-04 15:05:10.582,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,"CAH07-04\tGeneral, applied and forensic sciences",8,03/10/22 - 09/10/22,0.088333,2.041388,0.187500,0.000000,0.000000,0.000000,0.000000,...,NaN,2022-10-04 11:21:55.518,2022-10-04 09:45:52.993,NaN,2022-10-04 09:45:52.993,NaN,NaN,NaN,NaN,NaN
8,CAH03-01\tBiosciences,9,03/10/22 - 09/10/22,0.000000,0.003612,0.000000,0.000000,0.000000,0.000000,0.000000,...,NaN,NaN,2022-10-04 15:57:50.387,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,CAH11-01\tComputing,10,03/10/22 - 09/10/22,2.227223,0.001945,0.000000,0.000000,0.000000,0.000000,0.000000,...,NaN,2022-10-03 13:42:42.702,2022-10-04 15:53:35.542,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,CAH07-02\tChemistry,11,03/10/22 - 09/10/22,0.000000,2.108333,0.000000,0.000000,0.000000,0.000000,0.000000,...,NaN,NaN,2022-10-04 15:11:44.216,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,"CAH06-01\tAgriculture, food and related studies",12,03/10/22 - 09/10/22,0.189445,6.689167,0.000000,0.007778,0.049722,0.000000,0.000000,...,2022-10-04 14:33:38.001,2022-10-03 12:18:52.334,2022-10-03 12:18:24.798,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,CAH11-01\tComputing,13,03/10/22 - 09/10/22,0.000000,4.679167,0.044167,0.000000,0.000000,0.008888,0.000000,...,2022-10-04 14:14:27.735,NaN,2022-10-04 11:04:37.310,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,CAH10-01\tEngineering,14,03/10/22 - 09/10/22,0.000000,3.305000,0.000000,0.000000,0.000000,0.000000,0.000000,...,2022-10-04 12:40:49.049,2022-10-04 12:43:55.031,2022-10-04 12:49:18.623,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,CAH16-01\tLaw,15,03/10/22 - 09/10/22,0.276667,0.610833,0.000000,0.072500,0.000000,0.000000,0.001667,...,2022-10-03 15:12:22.128,NaN,2022-10-03 15:11:53.473,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,CAH17-01\tBusiness and management,16,03/10/22 - 09/10/22,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,CAH11-01\tComputing,17,03/10/22 - 09/10/22,0.000000,3.774167,0.021667,0.000000,0.000833,0.000000,1.690833,...,2022-10-04 10:45:16.351,2022-10-04 10:45:27.593,2022-10-04 10:45:35.702,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,CAH17-01\tBusiness and management,18,03/10/22 - 09/10/22,0.077222,2.310555,0.000000,0.000000,0.000000,0.000000,0.000000,...,2022-10-03 14:10:54.609,2022-10-03 14:10:53.314,2022-10-03 14:10:59.208,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,CAH15-02\tEconomics,19,03/10/22 - 09/10/22,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.016112,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,CAH17-01\tBusiness and management,20,03/10/22 - 09/10/22,0.000000,0.315000,0.000000,0.000000,0.000000,0.000000,0.000000,...,2022-10-04 23:03:09.998,NaN,2022-10-04 23:03:15.047,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,"CAH13-01\tArchitecture, building and planning",1,NaN,0.157222,2.300555,0.000000,0.000000,0.000000,0.000000,0.000000,...,NaN,NaN,2022-10-10 14:25:20.527,NaN,NaN,10/10/22 - 16/10/22,0.000000,2.0,0.0,NaN
21,CAH07-02\tChemistry,2,NaN,0.085278,1.924167,0.000000,0.000000,0.000000,0.000000,0.000000,...,2022-10-10 16:09:02.015,NaN,NaN,NaN,NaN,10/10/22 - 16/10/22,0.000000,0.0,0.0,NaN
22,CAH15-02\tEconomics,3,NaN,0.795833,2.403888,0.000000,0.000000,0.000000,0.000000,0.013612,...,2022-10-10 20:32:20.105,NaN,NaN,NaN,NaN,10/10/22 - 16/10/22,0.000000,4.0,0.0,NaN
23,CAH15-02\tEconomics,4,NaN,0.000000,0.000000,0.000000,0.000000,0.061112,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,10/10/22 - 16/10/22,0.000000,1.0,0.0,NaN
24,CAH17-01\tBusiness and management,5,NaN,0.337500,3.089167,0.000000,0.000000,0.000000,0.000000,0.000000,...,2022-10-11 14:13:01.991,NaN,2022-10-11 14:02:25.595,NaN,NaN,10/10/22 - 16/10/22,0.000000,1.0,0.0,NaN
25,CAH10-01\tEngineering,6,NaN,0.000000,3.400277,0.000000,0.000000,0.000000,0.018610,0.000000,...,2022-10-11 15:44:20.328,NaN,2022-10-11 15:31:37.239,NaN,NaN,10/10/22 - 16/10/22,0.000833,8.0,2.0,2022-10-15 11:25:51.164
26,CAH11-01\tComputing,7,NaN,0.000000,3.686667,0.000000,0.000000,2.393055,0.603612,0.000000,...,2022-10-15 00:40:03.300,2022-10-14 23:11:34.794,2022-10-11 14:03:04.643,NaN,NaN,10/10/22 - 16/10/22,0.033890,8.0,2.0,2022-10-15 01:00:35.391
27,"CAH07-04\tGeneral, applied and forensic sciences",8,NaN,0.184443,2.943888,0.000000,0.001388,0.000000,0.000000,0.000000,...,2022-10-11 14:24:44.977,NaN,NaN,NaN,NaN,10/10/22 - 16/10/22,0.000000,7.0,0.0,NaN
28,CAH03-01\tBiosciences,9,NaN,0.033612,0.000000,0.218333,0.000000,0.000000,0.000000,2.653612,...,2022-10-16 15:57:37.969,2022-10-16 15:57:34.365,2022-10-10 05:26:45.779,NaN,NaN,10/10/22 - 16/10/22,0.000000,1.0,0.0,NaN
29,CAH11-01\tComputing,10,NaN,0.378612,1.994723,0.000000,0.002778,0.000000,0.000000,0.000000,...,2022-10-10 16:04:40.905,2022-10-10 16:04:38.345,2022-10-11 14:05:10.031,NaN,NaN,10/10/22 - 16/10/22,0.000000,0.0,0.0,NaN
30,CAH07-02\tChemistry,11,NaN,0.000000,2.746945,0.012500,0.000000,0.004722,0.016667,0.000000,...,NaN,NaN,2022-10-11 14:09:43.154,NaN,NaN,10/10/22 - 16/10/22,0.000000,3.0,0.0,NaN
31,"CAH06-01\tAgriculture, food and related studies",12,NaN,0.380000,3.200833,0.000000,0.000000,0.000000,6.344167,5.215278,...,2022-10-10 19:23:39.544,2022-10-10 19:31:53.459,NaN,NaN,NaN,10/10/22 - 16/10/22,2.261390,7.0,4.0,2022-10-15 18:11:28.679
32,CAH11-01\tComputing,13,NaN,0.005833,1.176667,0.000000,0.000000,0.398055,0.050833,0.000000,...,2022-10-14 20:25:19.077,NaN,NaN,NaN,NaN,10/10/22 - 16/10/22,0.005278,1.0,2.0,2022-10-14 19:56:26.777
33,CAH10-01\tEngineering,14,NaN,0.000000,4.493057,0.027222,0.000000,0.000000,0.000000,0.000000,...,NaN,NaN,2022-10-11 14:49:16.366,NaN,NaN,10/10/22 - 16/10/22,0.000000,4.0,0.0,NaN
34,CAH16-01\tLaw,15,NaN,4.064723,0.951112,0.000000,0.000000,0.000000,0.005833,2.123612,...,2022-10-16 16:20:07.522,NaN,2022-10-10 15:10:22.792,NaN,NaN,10/10/22 - 16/10/22,0.002500,5.0,2.0,2022-10-15 16:03:02.428
35,CAH17-01\tBusiness and management,16,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,10/10/22 - 16/10/22,0.000000,0.0,0.0,NaN
36,CAH11-01\tComputing,17,NaN,0.000000,1.222500,0.000000,0.000000,0.022222,0.000000,0.013612,...,2022-10-11 09:36:16.785,NaN,NaN,NaN,NaN,10/10/22 - 16/10/22,0.000000,7.0,0.0,NaN
37,CAH17-01\tBusiness and management,18,NaN,1.826945,4.698055,0.000000,0.000000,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,10/10/22 - 16/10/22,0.000000,6.0,0.0,NaN
38,CAH15-02\tEconomics,19,NaN,0.000000,0.270833,0.000000,0.000000,0.000000,0.000000,0.000000,...,NaN,NaN,2022-10-11 14:47:55.454,NaN,NaN,10/10/22 - 16/10/22,0.000000,0.0,0.0,NaN
39,CAH17-01\tBusiness and management,20,NaN,1.182778,1.624445,0.000000,0.000000,0.000000,0.000000,0.000000,...,2022-10-10 11:57:15.185,NaN,2022-10-10 11:57:22.034,NaN,NaN,10/10/22 - 16/10/22,0.000000,5.0,0.0,NaN

In [4]:
# renaming columns with spaces and special characters
week1_democo2 = pd.read_excel(xls,'Week 1',skiprows=1)
week1_democo2.columns=week1_democo2.columns.str.replace(' ','_').str.replace(',','').str.lower().str.replace("-",'_').str.replace("?",'').str.replace("(",'').str.replace(")",'').str.replace('.','').str.replace('&','').str.replace(":",'')
week1_democo2 =week1_democo2.iloc[0:20:, 4:]
df = week1_democo2
df = pd.DataFrame(df)

df_scv = df.to_csv('csv_data/week1.csv', index=False)

In [5]:
# renaming columns with spaces and special characters
week1_democo2 = pd.read_excel(xls,'Week 2',skiprows=1)
week1_democo2.columns=week1_democo2.columns.str.replace(' ','_').str.replace(',','').str.lower().str.replace("-",'_').str.replace("?",'').str.replace("(",'').str.replace(")",'').str.replace('.','').str.replace('&','').str.replace(":",'')
week1_democo2 =week1_democo2.iloc[0:20, 4:]
df = week1_democo2
df = pd.DataFrame(df)

df.to_csv('csv_data/week2.csv', index=False)

In [ ]:
# renaming columns with duplicate names
df.columns.values[0]  =  'total_marks'
df.columns.values[18] = 'std_act_assignments'
df.columns.values[19] = 'std_act_learning_materials'
df.columns.values[20] = 'std_act_module_information_handbook1'
df.columns.values[21] = 'std_act_reading_list'
df.columns.values[22] = 'std_act_week1'
df.columns.values[23] = 'std_act_week2'
df.columns.values[24] = 'no_of_times_accessed_assignments'
df.columns.values[25] = 'no_of_times_accessed_learning_materials'
df.columns.values[26] = 'no_of_times_accessed_module_information_handbook1'
df.columns.values[27] = 'no_of_times_accessedreading_list'
df.columns.values[28] = 'no_of_times_week1'
df.columns.values[29] = 'no_of_times_week2'
df.columns.values[30] = 'initial_access_assignments'
df.columns.values[31] = 'initial_access_learning_materials'
df.columns.values[32] = 'initial_access_information_handbook1'
df.columns.values[33] = 'initial_access_reading_list'
df.columns.values[34] = 'initial_access_week1'
df.columns.values[35] = 'initial_access_week2'

In [126]:
#bringing  week1 and week two of std activities into rows
try:
  df = pd.melt(df, id_vars=['total_marks', 'list_of_countries',
       'what_is_your_year_of_birth_just_the_year_eg_1995_',
       'how_do_you_describe_yourself___selected_choice',
       'what_is_your_first_degree_subject_area', 'student_id',
       'date_range__week_1', 'monday', 'tuesday', 'wednesday', 'thursday',
       'friday', 'saturday', 'sunday', 'student_time_in_course',
       'avg_time_per_user', 'total_items', 'total_logins',
       'std_act_assignments', 'std_act_learning_materials',
       'std_act_module_information_handbook1', 'std_act_reading_list',
       'no_of_times_accessed_assignments',
       'no_of_times_accessed_learning_materials',
       'no_of_times_accessed_module_information_handbook1',
       'no_of_times_accessedreading_list', 'no_of_times_week1',
       'no_of_times_week2', 'initial_access_assignments',
       'initial_access_learning_materials',
       'initial_access_information_handbook1', 'initial_access_reading_list',
       'initial_access_week1', 'initial_access_week2', 'unnamed_40'
      ],
          value_vars=['std_act_week1', 'std_act_week2'], var_name='std_act_weeks', value_name='hours_spent')
except Exception as e:
  print("Error in melting the DataFrame:", e)
  raise

In [122]:
#bringing first week from columns into the rows
try:
  df = pd.melt(df, id_vars=['total_marks', 'list_of_countries',
       'what_is_your_year_of_birth_just_the_year_eg_1995_',
       'how_do_you_describe_yourself___selected_choice',
       'what_is_your_first_degree_subject_area', 'student_id',
       'date_range__week_1', 'monday', 'tuesday', 'wednesday', 'thursday',
       'friday', 'saturday', 'sunday', 'student_time_in_course',
       'avg_time_per_user', 'total_items', 'total_logins',
       'std_act_assignments', 'std_act_learning_materials',
       'std_act_module_information_handbook1', 'std_act_reading_list',
       'no_of_times_accessed_assignments',
       'no_of_times_accessed_learning_materials',
       'no_of_times_accessed_module_information_handbook1',
       'no_of_times_accessedreading_list',
       'initial_access_assignments',
       'initial_access_learning_materials',
       'initial_access_information_handbook1', 'initial_access_reading_list',
       'initial_access_week1', 'initial_access_week2', 'unnamed_40',
       'hours_spent','std_act_weeks'
      ],
          value_vars=['no_of_times_week1', 'no_of_times_week2'], var_name='no_of_times_week', value_name='no_of_times_accessed')
except Exception as e:
  print("Error in melting the DataFrame:", e)
  raise

In [127]:
df[(df['student_id'] == 1)]

,total_marks,list_of_countries,what_is_your_year_of_birth_just_the_year_eg_1995_,how_do_you_describe_yourself___selected_choice,what_is_your_first_degree_subject_area,student_id,date_range__week_1,monday,tuesday,wednesday,...,no_of_times_week2,initial_access_assignments,initial_access_learning_materials,initial_access_information_handbook1,initial_access_reading_list,initial_access_week1,initial_access_week2,unnamed_40,std_act_weeks,hours_spent
0,60.0,Nigeria,1996,Male,"CAH13-01\tArchitecture, building and planning",1,03/10/22 - 09/10/22,0.0,0.005278,0.014722,...,0,NaN,2022-10-04 15:45:00.718,NaT,NaT,2022-10-04 15:45:03.544,NaT,NaT,std_act_week1,0.016388
212,60.0,Nigeria,1996,Male,"CAH13-01\tArchitecture, building and planning",1,03/10/22 - 09/10/22,0.0,0.005278,0.014722,...,0,NaN,2022-10-04 15:45:00.718,NaT,NaT,2022-10-04 15:45:03.544,NaT,NaT,std_act_week2,0.000000

In [37]:
#bringing first week from columns into the rows
try:
  df = pd.melt(df, id_vars=['total_marks', 'list_of_countries',
       'what_is_your_year_of_birth_just_the_year_eg_1995_',
       'how_do_you_describe_yourself___selected_choice',
       'what_is_your_first_degree_subject_area', 'student_id',
       'date_range__week_1', 'monday', 'tuesday', 'wednesday', 'thursday',
       'friday', 'saturday', 'sunday', 'student_time_in_course',
       'avg_time_per_user', 'total_items', 'total_logins',
       'std_act_assignments', 'std_act_learning_materials',
       'std_act_module_information_handbook1', 'std_act_reading_list',
       'no_of_times_accessed_assignments',
       'no_of_times_accessed_learning_materials',
       'no_of_times_accessed_module_information_handbook1',
       'no_of_times_accessedreading_list',
       'initial_access_assignments',
       'initial_access_learning_materials',
       'initial_access_information_handbook1', 'initial_access_reading_list', 'unnamed_40',
       'hours_spent','std_act_weeks', 'no_of_times_accessed', 'no_of_times_week'
      ],
          value_vars=['initial_access_week2', 'initial_access_week1'], var_name='initial_access_week', value_name='initial_access_date')
except Exception as e:
  print("Error in melting the DataFrame:", e)
  raise

In [69]:
# renaming columns with spaces and special characters
week2_democo2 = pd.read_excel(xls,'Week 2',skiprows=1)
week2_democo2.columns=week2_democo2.columns.str.replace(' ','_').str.replace(',','').str.lower().str.replace("-",'_').str.replace("?",'').str.replace("(",'').str.replace(")",'').str.replace('.','').str.replace('&','').str.replace(":",'')
df = week2_democo2 =week2_democo2.iloc[:, 4:]

In [70]:
# renaming columns with duplicate names
df.columns.values[0] = 'total_marks'
df.columns.values[18] = 'std_act_assignments'
df.columns.values[19] = 'std_act_learning_materials'
df.columns.values[20] = 'std_act_module_information_handbook1'
df.columns.values[21] = 'std_act_reading_list'
df.columns.values[22] = 'std_act_week1'
df.columns.values[23] = 'std_act_week2'
df.columns.values[24] = 'std_act_week3'
df.columns.values[25] = 'no_of_times_accessed_assignments'
df.columns.values[26] = 'no_of_times_accessed_learning_materials'
df.columns.values[27] = 'no_of_times_accessed_module_information_handbook1'
df.columns.values[28] = 'no_of_times_accessedreading_list'
df.columns.values[29] = 'no_of_times_week1'
df.columns.values[30] = 'no_of_times_week2'
df.columns.values[31] = 'no_of_times_week3'
df.columns.values[32] = 'initial_access_assignments'
df.columns.values[33] = 'initial_access_learning_materials'
df.columns.values[34] = 'initial_access_information_handbook1'
df.columns.values[35] = 'initial_access_reading_list'
df.columns.values[36] = 'initial_access_week1'
df.columns.values[37] = 'initial_access_week2'
df.columns.values[38] = 'initial_access_week3'
df2 = df.copy()

In [50]:
df2

,total_marks,list_of_countries,what_is_your_year_of_birth_just_the_year_eg_1995_,how_do_you_describe_yourself___selected_choice,what_is_your_first_degree_subject_area,student_id,date_range__week_2,monday,tuesday,wednesday,...,no_of_times_week1,no_of_times_week2,no_of_times_week3,initial_access_assignments,initial_access_learning_materials,initial_access_information_handbook1,initial_access_reading_list,initial_access_week1,initial_access_week2,initial_access_week3
0,60.0,Nigeria,1996,Male,"CAH13-01\tArchitecture, building and planning",1,10/10/22 - 16/10/22,0.157222,2.300555,0.0,...,1,2,0,NaN,2022-10-10 14:16:49.242,NaT,NaT,2022-10-10 14:25:20.527,2022-10-10 14:16:55.852,NaT
1,70.0,Nigeria,1996,Male,CAH07-02\tChemistry,2,10/10/22 - 16/10/22,0.085278,1.924167,0.0,...,1,0,0,NaN,2022-10-10 16:07:41.250,2022-10-10 16:09:02.015,NaT,NaT,2022-10-10 16:07:44.741,NaT
2,65.0,Nigeria,1990,Female,CAH15-02\tEconomics,3,10/10/22 - 16/10/22,0.795833,2.403888,0.0,...,0,4,0,NaN,2022-10-10 20:32:28.517,2022-10-10 20:32:20.105,NaT,NaT,2022-10-10 20:32:35.934,NaT
3,55.0,Nigeria,1991,Male,CAH15-02\tEconomics,4,10/10/22 - 16/10/22,0.000000,0.000000,0.0,...,0,1,0,NaN,2022-10-14 12:27:18.186,NaT,NaT,NaT,2022-10-14 12:27:22.967,NaT
4,65.0,Pakistan,1998,Male,CAH17-01\tBusiness and management,5,10/10/22 - 16/10/22,0.337500,3.089167,0.0,...,3,1,0,NaN,2022-10-11 14:02:17.998,2022-10-11 14:13:01.991,NaT,2022-10-11 14:02:25.595,2022-10-11 15:29:04.753,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,60.4,India,1992,Male,CAH19-01\tEnglish studies,208,09/10/23 - 15/10/23,0.000000,1.403888,0.0,...,4,2,0,NaN,2023-10-10 14:00:37.642,NaT,NaT,2023-10-10 14:01:00.490,2023-10-10 14:00:39.370,NaT
208,64.0,Bangladesh,1996,Female,CAH17-01\tBusiness and management,209,09/10/23 - 15/10/23,2.835000,1.852500,0.0,...,3,5,1,NaN,2023-10-09 22:38:40.351,NaT,2023-10-09 22:38:36.911,2023-10-09 19:59:06.028,2023-10-09 22:39:01.643,2023-10-16 01:47:34.795
209,73.0,Sri Lanka,1996,Female,CAH11-01\tComputing,210,09/10/23 - 15/10/23,0.000000,1.731112,0.0,...,1,1,2,NaN,2023-10-10 14:05:59.836,NaT,NaT,2023-10-10 14:06:03.021,2023-10-10 15:37:15.039,2023-10-10 15:45:54.537
210,61.8,Myanmar,1998,Female,CAH11-01\tComputing,211,09/10/23 - 15/10/23,0.020000,1.141945,0.0,...,4,13,1,NaN,2023-10-10 12:10:10.035,NaT,NaT,2023-10-10 12:21:11.116,2023-10-10 12:10:14.445,2023-10-15 16:06:25.528
211,63.0,United States of America,2001,Male,CAH11-01\tComputing,212,09/10/23 - 15/10/23,0.023055,0.080833,0.0,...,1,1,1,NaN,2023-10-09 18:10:56.032,NaT,NaT,2023-10-09 18:11:00.881,2023-10-10 15:37:36.341,2023-10-10 15:41:36.312

In [71]:
#bringing first week from columns into the rows
try:
  df2 = pd.melt(df2, id_vars=['total_marks', 'list_of_countries',
       'what_is_your_year_of_birth_just_the_year_eg_1995_',
       'how_do_you_describe_yourself___selected_choice',
       'what_is_your_first_degree_subject_area', 'student_id',
       'date_range__week_2', 'monday', 'tuesday', 'wednesday', 'thursday',
       'friday', 'saturday', 'sunday', 'student_time_in_course',
       'avg_time_per_user', 'total_items', 'total_logins',
       'std_act_assignments', 'std_act_learning_materials',
       'std_act_module_information_handbook1', 'std_act_reading_list',
       'no_of_times_accessed_assignments',
       'no_of_times_accessed_learning_materials',
       'no_of_times_accessed_module_information_handbook1',
       'no_of_times_accessedreading_list', 'no_of_times_week1',
       'no_of_times_week2', 'no_of_times_week3', 'initial_access_assignments',
       'initial_access_learning_materials',
       'initial_access_information_handbook1', 'initial_access_reading_list',
       'initial_access_week1', 'initial_access_week2', 'initial_access_week3'
      ],
          value_vars=['std_act_week1', 'std_act_week2','std_act_week3'], var_name='std_act_week', value_name='hours_spent')
except Exception as e:
  print("Error in melting the DataFrame:", e)
  raise

In [63]:
df2.columns

Index(['total_marks', 'list_of_countries',
       'what_is_your_year_of_birth_just_the_year_eg_1995_',
       'how_do_you_describe_yourself___selected_choice',
       'what_is_your_first_degree_subject_area', 'student_id',
       'date_range__week_2', 'monday', 'tuesday', 'wednesday', 'thursday',
       'friday', 'saturday', 'sunday', 'student_time_in_course',
       'avg_time_per_user', 'total_items', 'total_logins',
       'std_act_assignments', 'std_act_learning_materials',
       'std_act_module_information_handbook1', 'std_act_reading_list',
       'no_of_times_accessed_assignments',
       'no_of_times_accessed_learning_materials',
       'no_of_times_accessed_module_information_handbook1',
       'no_of_times_accessedreading_list', 'no_of_times_week1',
       'no_of_times_week2', 'no_of_times_week3', 'initial_access_assignments',
       'initial_access_learning_materials',
       'initial_access_information_handbook1', 'initial_access_reading_list',
       'initial_access_week1', 'initial_access_week2', 'initial_access_week3',
       'std_act_week', 'hours_spent'],
      dtype='object')

In [72]:
#bringing second week from columns into the rows
try:
  df2 = pd.melt(df2, id_vars=['total_marks', 'list_of_countries',
       'what_is_your_year_of_birth_just_the_year_eg_1995_',
       'how_do_you_describe_yourself___selected_choice',
       'what_is_your_first_degree_subject_area', 'student_id',
       'date_range__week_2', 'monday', 'tuesday', 'wednesday', 'thursday',
       'friday', 'saturday', 'sunday', 'student_time_in_course',
       'avg_time_per_user', 'total_items', 'total_logins',
       'std_act_assignments', 'std_act_learning_materials',
       'std_act_module_information_handbook1', 'std_act_reading_list',
       'no_of_times_accessed_assignments',
       'no_of_times_accessed_learning_materials',
       'no_of_times_accessed_module_information_handbook1',
       'no_of_times_accessedreading_list','initial_access_assignments',
       'initial_access_learning_materials',
       'initial_access_information_handbook1', 'initial_access_reading_list',
       'initial_access_week1', 'initial_access_week2', 'initial_access_week3',
       'std_act_week', 'hours_spent'
      ],
          value_vars=['no_of_times_week1', 'no_of_times_week2','no_of_times_week3'],
          var_name='no_of_times_weeks', value_name='no_of_times')
except Exception as e:
  print("Error in melting the DataFrame:", e)
  raise

In [73]:
#bringing second week from columns into the rows
try:
  df2 = pd.melt(df2, id_vars=['total_marks', 'list_of_countries',
       'what_is_your_year_of_birth_just_the_year_eg_1995_',
       'how_do_you_describe_yourself___selected_choice',
       'what_is_your_first_degree_subject_area', 'student_id',
       'date_range__week_2', 'monday', 'tuesday', 'wednesday', 'thursday',
       'friday', 'saturday', 'sunday', 'student_time_in_course',
       'avg_time_per_user', 'total_items', 'total_logins',
       'std_act_assignments', 'std_act_learning_materials',
       'std_act_module_information_handbook1', 'std_act_reading_list',
       'no_of_times_accessed_assignments',
       'no_of_times_accessed_learning_materials',
       'no_of_times_accessed_module_information_handbook1',
       'no_of_times_accessedreading_list','initial_access_assignments',
       'initial_access_learning_materials',
       'initial_access_information_handbook1', 'initial_access_reading_list',

       'std_act_week', 'hours_spent'
      ],
          value_vars=['initial_access_week1', 'initial_access_week2', 'initial_access_week3'],
          var_name='initial_access_weeks', value_name='initial_access_date')
except Exception as e:
  print("Error in melting the DataFrame:", e)
  raise

In [113]:
df2# renaming columns with spaces and special characters
df3 = pd.read_excel(xls,'Week 3',skiprows=1)
df3.columns=df3.columns.str.replace(' ','_').str.replace(',','').str.lower().str.replace("-",'_').str.replace("?",'').str.replace("(",'').str.replace(")",'').str.replace('.','').str.replace('&','').str.replace(":",'')
df3 =df3.iloc[:, 4:]
[i for i in enumerate(df3.columns)]
df= df3.copy()

In [114]:
# renaming columns with duplicate names
df.columns.values[0] = 'total_marks'
df.columns.values[18] = 'std_act_assignments'
df.columns.values[19] = 'std_act_learning_materials'
df.columns.values[20] = 'std_act_module_information_handbook1'
df.columns.values[21] = 'std_act_reading_list'
df.columns.values[22] = 'std_act_week1'
df.columns.values[23] = 'std_act_week2'
df.columns.values[24] = 'std_act_week3'
df.columns.values[25] = 'std_act_week4'
df.columns.values[26] = 'no_of_times_accessed_assignments'
df.columns.values[27] = 'no_of_times_accessed_learning_materials'
df.columns.values[28] = 'no_of_times_accessed_module_information_handbook1'
df.columns.values[29] = 'no_of_times_accessedreading_list'
df.columns.values[30] = 'no_of_times_week1'
df.columns.values[31] = 'no_of_times_week2'
df.columns.values[32] = 'no_of_times_week3'
df.columns.values[33] = 'no_of_times_week4'
df.columns.values[34] = 'initial_access_assignments'
df.columns.values[35] = 'initial_access_learning_materials'
df.columns.values[36] = 'initial_access_information_handbook1'
df.columns.values[37] = 'initial_access_reading_list'
df.columns.values[38] = 'initial_access_week1'
df.columns.values[39] = 'initial_access_week2'
df.columns.values[40] = 'initial_access_week3'
df.columns.values[41] = 'initial_access_week4' 
df3 = df.copy()

In [96]:
df3.shape

(212, 42)

In [109]:
dff =pd.merge(dff,df3,how= 'inner',on='student_id')
dff[(dff['student_id'] == 1)]

,student_id,std_act_week1_x,std_act_week22,total_marks,list_of_countries,what_is_your_year_of_birth_just_the_year_eg_1995_,how_do_you_describe_yourself___selected_choice,what_is_your_first_degree_subject_area,date_range__week_3,monday,...,no_of_times_week3,no_of_times_week4,initial_access_assignments,initial_access_learning_materials,initial_access_information_handbook1,initial_access_reading_list,initial_access_week1,initial_access_week2,initial_access_week3,initial_access_week4
0,1,std_act_week1,0.000000,60.0,Nigeria,1996,Male,"CAH13-01\tArchitecture, building and planning",17/10/22 - 23/10/22,0.0,...,2,0,NaN,2022-10-18 14:10:31.452,NaT,NaT,NaT,NaT,2022-10-18 14:10:35.157,NaT
212,1,std_act_week2,0.000000,60.0,Nigeria,1996,Male,"CAH13-01\tArchitecture, building and planning",17/10/22 - 23/10/22,0.0,...,2,0,NaN,2022-10-18 14:10:31.452,NaT,NaT,NaT,NaT,2022-10-18 14:10:35.157,NaT
424,1,std_act_week3,2.188333,60.0,Nigeria,1996,Male,"CAH13-01\tArchitecture, building and planning",17/10/22 - 23/10/22,0.0,...,2,0,NaN,2022-10-18 14:10:31.452,NaT,NaT,NaT,NaT,2022-10-18 14:10:35.157,NaT
636,1,std_act_week4,0.000000,60.0,Nigeria,1996,Male,"CAH13-01\tArchitecture, building and planning",17/10/22 - 23/10/22,0.0,...,2,0,NaN,2022-10-18 14:10:31.452,NaT,NaT,NaT,NaT,2022-10-18 14:10:35.157,NaT

In [116]:
dff

     student_id  std_act_week1  std_act_week22
0             1  std_act_week1        0.000000
1             2  std_act_week1        0.000000
2             3  std_act_week1        0.000000
3             4  std_act_week1        0.000000
4             5  std_act_week1        0.000000
..          ...            ...             ...
843         208  std_act_week4        0.000000
844         209  std_act_week4        0.000000
845         210  std_act_week4        0.066667
846         211  std_act_week4        0.006112
847         212  std_act_week4        0.025278

[848 rows x 3 columns]

In [115]:
dff = df[['std_act_week1', 'std_act_week2', 'std_act_week3', 'std_act_week4', 'student_id']]


#bringing second week from columns into the rows
try:
  dff = pd.melt(dff, id_vars=['student_id'],
      
          value_vars=['std_act_week1', 'std_act_week2', 'std_act_week3', 'std_act_week4'],
          var_name='std_act_week1', value_name='std_act_week22')
except Exception as e:
  print("Error in melting the DataFrame:", e)
  raise

In [79]:
df3.columns

Index(['total_marks', 'list_of_countries',
       'what_is_your_year_of_birth_just_the_year_eg_1995_',
       'how_do_you_describe_yourself___selected_choice',
       'what_is_your_first_degree_subject_area', 'student_id',
       'date_range__week_3', 'monday', 'tuesday', 'wednesday', 'thursday',
       'friday', 'saturday', 'sunday', 'student_time_in_course',
       'avg_time_per_user', 'total_items', 'total_logins',
       'std_act_assignments', 'std_act_learning_materials',
       'std_act_module_information_handbook1', 'std_act_reading_list',
       'std_act_week1', 'std_act_week2', 'std_act_week3', 'std_act_week4',
       'no_of_times_accessed_assignments',
       'no_of_times_accessed_learning_materials',
       'no_of_times_accessed_module_information_handbook1',
       'no_of_times_accessedreading_list', 'no_of_times_week1',
       'no_of_times_week2', 'no_of_times_week3', 'no_of_times_week4',
       'initial_access_assignments', 'initial_access_learning_materials',
       'initial_access_information_handbook1', 'initial_access_reading_list',
       'initial_access_week1', 'initial_access_week2', 'initial_access_week3',
       'initial_access_week4'],
      dtype='object')

In [ ]:
#bringing second week from columns into the rows
try:
  df2 = pd.melt(df2, id_vars=['total_marks', 'list_of_countries',
       'what_is_your_year_of_birth_just_the_year_eg_1995_',
       'how_do_you_describe_yourself___selected_choice',
       'what_is_your_first_degree_subject_area', 'student_id',
       'date_range__week_3', 'monday', 'tuesday', 'wednesday', 'thursday',
       'friday', 'saturday', 'sunday', 'student_time_in_course',
       'avg_time_per_user', 'total_items', 'total_logins',
       'std_act_assignments', 'std_act_learning_materials',
       'std_act_module_information_handbook1', 'std_act_reading_list',
       
       'no_of_times_accessed_assignments',
       'no_of_times_accessed_learning_materials',
       'no_of_times_accessed_module_information_handbook1',
       'no_of_times_accessedreading_list', 'no_of_times_week1',
       'no_of_times_week2', 'no_of_times_week3', 'no_of_times_week4',
       'initial_access_assignments', 'initial_access_learning_materials',
       'initial_access_information_handbook1', 'initial_access_reading_list',
       'initial_access_week1', 'initial_access_week2', 'initial_access_week3',
       'initial_access_week4'
      ],
          value_vars=['std_act_week1', 'std_act_week2', 'std_act_week3', 'std_act_week4',],
          var_name='std_act_week1', value_name='no_of_times')
except Exception as e:
  print("Error in melting the DataFrame:", e)
  raise